# Generated by Django 5.2.2 on 2025-11-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
    ]
