# Generated by Django 5.2.2 on 2025-11-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundlab_store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
